---
name: WeatherChunks
author: Mysonied
version: 0.0.1
main: Mysonied\WeatherChunks\Main
api: 5.0.0
src-namespace-prefix: Mysonied\WeatherChunks
description: Per-chunk weather system for PM5
commands:
  weatherchunks:
    description: Manage per-chunk weather
    usage: "/weatherchunks <clear|rain|thunder|map>"
    permission: weatherchunks.command

permissions:
  weatherchunks.command:
    description: Allows using /weatherchunks
    default: op
...
